import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "../theme-provider";
import ToastProvider from "@/components/ToastProvider/ToastProvider";
import Sidebar from "@/components/Sidebar/Sidebar";
import { headers } from "next/headers";
import { UserProvider } from "../context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCurrentUser() {
  const cookie = (await headers()).get("cookie");

  try {
    const res = await fetch("http://localhost:8000/api/v1/users/me", {
      headers: {
        cookie: cookie ?? "",
      },
    });
    if (res.status === 401) return null;

    const json = await res.json();
    return json.data;
  } catch (error) {
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider user={user}>
          <Sidebar>
            <MuiThemeProvider>
              <ToastProvider />
              {children}
            </MuiThemeProvider>
          </Sidebar>
        </UserProvider>
      </body>
    </html>
  );
}
