import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "../theme-provider";
import ToastProvider from "@/components/ToastProvider/ToastProvider";
import Sidebar from "@/components/Sidebar/Sidebar";
import { UserProvider } from "../context/UserContext";
const apiUrl = process.env.NEXT_PUBLIC_API_URL;
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getCurrentUser() {

  const cookieStore = await cookies(); // Next.js CookieStore
  const accessToken = cookieStore.get("accessToken")?.value; // get specific cookie
  console.log(accessToken)

  try {
    const res = await fetch(`${apiUrl}/api/v1/users/me`, {
      headers: {
        // forward only the cookie needed
        cookie: accessToken ? `accessToken=${accessToken}` : "",
      },
      cache: "no-store", // important for SSR
      credentials: "include", // optional
    });

    if (!res.ok) return null;

    const json = await res.json();
    return json.data;
  } catch (error) {
    console.error(error);
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const user = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <Sidebar>
            <MuiThemeProvider>
              <ToastProvider />
              {children}
            </MuiThemeProvider>
          </Sidebar>
        </UserProvider>
      </body>
    </html>
  );
}
