import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../(main)/globals.css";
import MuiThemeProvider from "../theme-provider";
import ToastProvider from "@/components/ToastProvider/ToastProvider";
import Sidebar from "@/components/Sidebar/Sidebar";
import { headers } from "next/headers";
import { UserProvider } from "../context/UserContext";
import StudioSidebar from "@/components/Sidebar/StudioSidebar";
const apiUrl = process.env.NEXT_PUBLIC_API_URL;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchWithCookies(url: string) {
  const cookie = (await headers()).get("cookie");

  return fetch(url, {
    headers: {
      cookie: cookie ?? "",
    },
  });
}

async function refreshToken() {
  console.log("refresh");
  try {
    const res = await fetchWithCookies(`${apiUrl}/api/v1/users/refresh-token`);
    return res.ok;
  } catch {
    return false;
  }
}

async function getCurrentUser() {
  try {
    // 1️ First attempt
    let res = await fetchWithCookies(`${apiUrl}/api/v1/users/me`);

    // 2️ If unauthorized → try refresh
    if (res.status === 401) {
      const refreshed = await refreshToken();
      if (!refreshed) return null;

      // 3️ Retry after refresh
      res = await fetchWithCookies(`${apiUrl}/api/v1/users/me`);
      if (!res.ok) return null;
    }

    const json = await res.json();
    return json.data ?? null;
  } catch {
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider user={user}>
          <StudioSidebar>
            <MuiThemeProvider>
              <ToastProvider />
              {children}
            </MuiThemeProvider>
          </StudioSidebar>
        </UserProvider>
      </body>
    </html>
  );
}
