import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../(main)/globals.css";
import MuiThemeProvider from "../theme-provider";
import ToastProvider from "@/components/ToastProvider/ToastProvider";
import { UserProvider } from "../context/UserContext";
import StudioSidebar from "@/components/Sidebar/StudioSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <StudioSidebar>
            <MuiThemeProvider>
              <ToastProvider />
              {children}
            </MuiThemeProvider>
          </StudioSidebar>
        </UserProvider>
      </body>
    </html>
  );
}
